name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: namankudesia
          svg_out_path: dist/github-contribution-grid-snake.svg

      - uses: actions/upload-artifact@v4  # Updated version
        with:
          name: snake-gif
          path: dist/github-contribution-grid-snake.svg
