name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Snake Animation
        id: snake
        uses: Platane/snk@master
        with:
          github_user_name: namankudesia  # Replace with your GitHub username
          svg_out_path: dist/github-contribution-grid-snake.svg  # Correct output path

      - name: Upload Snake Animation
        uses: actions/upload-artifact@v4  # Update to latest version
        with:
          name: snake-gif
          path: dist/github-contribution-grid-snake.svg
